export enum Pdutype {
    UNDEFINED = 0,
    LOGIN_REQUEST = 1,
    LOGIN_RESPONSE = 2,
    LOGOUT_REQUEST = 3,
    LOGOUT_RESPONSE = 4,
    CHAT_MESSAGE_REQUEST = 5,
    CHAT_MESSAGE_RESPONSE = 6,
    CHAT_MESSAGE_EVENT = 7,
    LOGIN_EVENT = 8,
    LOGOUT_EVENT = 9,
    CHAT_MESSAGE_EVENT_CONFIRM = 10,
    LOGIN_EVENT_CONFIRM = 11,
    LOGOUT_EVENT_CONFIRM = 12
}
