export enum Pdutype {
    UNDEFINED = <any>"UNDEFINED",
    LOGIN_REQUEST = <any>"LOGIN_REQUEST",
    LOGIN_RESPONSE = <any>"LOGIN_RESPONSE",
    LOGOUT_REQUEST = <any>"LOGOUT_REQUEST",
    LOGOUT_RESPONSE = <any>"LOGOUT_RESPONSE",
    CHAT_MESSAGE_REQUEST = <any>"CHAT_MESSAGE_REQUEST",
    CHAT_MESSAGE_RESPONSE = <any>"CHAT_MESSAGE_RESPONSE",
    CHAT_MESSAGE_EVENT = <any>"CHAT_MESSAGE_EVENT",
    LOGIN_EVENT = <any>"LOGIN_EVENT",
    LOGOUT_EVENT = <any>"LOGOUT_EVENT",
    CHAT_MESSAGE_EVENT_CONFIRM = <any>"CHAT_MESSAGE_EVENT_CONFIRM",
    LOGIN_EVENT_CONFIRM = <any>"LOGIN_EVENT_CONFIRM",
    LOGOUT_EVENT_CONFIRM = <any>"LOGOUT_EVENT_CONFIRM"
}
